name: FreeLearn App Build and Deploy

on:
  push:
    branches:
      - master
   

env:
  AZURE_WEBAPP_NAME: gitsample3-2    # set this to your application's name
  

  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Run MSBuild
        run: msbuild .\gitsample3.sln
        
      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
   
    steps:
    
    
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_FREELEARN_SP }}
        env: # Or as an environment variable
         creds: ${{ secrets.AZURE_FREELEARN_SP }}
          
          
      - name: Run Azure webapp deploy action using secret
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
